# Generated by Django 3.2.9 on 2021-11-16 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
            ],
            options={
                'verbose_name': 'brand',
                'verbose_name_plural': 'brands',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='description')),
                ('presentation', models.CharField(max_length=255, verbose_name='presentation')),
                ('barcode', models.CharField(max_length=128, verbose_name='barcode')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.brand', verbose_name='brand')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.category', verbose_name='category')),
            ],
        ),
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(max_length=128, verbose_name='barcode')),
            ],
            options={
                'verbose_name': 'scan',
                'verbose_name_plural': 'scans',
            },
        ),
        migrations.CreateModel(
            name='SellingPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='unit price')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.product', verbose_name='product')),
            ],
            options={
                'verbose_name': 'selling price',
                'verbose_name_plural': 'selling prices',
            },
        ),
        migrations.CreateModel(
            name='SaleProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_purchase_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='unit purchase price')),
                ('unit_selling_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='unit selling price')),
                ('sold', models.BooleanField(default=False, verbose_name='sold')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='quantity')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product', verbose_name='product')),
            ],
            options={
                'verbose_name': 'sale product',
                'verbose_name_plural': 'sale products',
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sold', models.BooleanField(default=False, verbose_name='sold')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('sold_at', models.DateTimeField(null=True, verbose_name='sold at')),
                ('income', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='income')),
                ('gross_profit', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='gross profit')),
                ('products', models.ManyToManyField(to='core.SaleProduct', verbose_name='products')),
            ],
            options={
                'verbose_name': 'sale',
                'verbose_name_plural': 'sales',
            },
        ),
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='quantity')),
                ('unit_purchase_price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='unit purchase price')),
                ('package_purchase_price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='package purchase price')),
                ('units_per_package', models.PositiveIntegerField(default=1, verbose_name='units per package')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product', verbose_name='product')),
            ],
            options={
                'verbose_name': 'lot',
                'verbose_name_plural': 'lots',
                'get_latest_by': 'created_at',
            },
        ),
    ]
